export const GET_POSTS_ADMIN = 'GET_POSTS_ADMIN';
export const GET_POSTS_SUCCESS_ADMIN = 'GET_POSTS_SUCCESS_ADMIN';
export const GET_POSTS_FAILURE_ADMIN = 'GET_POSTS_FAILURE_ADMIN';
export const POST_POSTS_ADMIN = 'POST_POSTS_ADMIN';
export const POST_POSTS_SUCCESS_ADMIN = 'POST_POSTS_SUCCESS_ADMIN';
export const POST_POSTS_FAILURE_ADMIN = 'POST_POSTS_FAILURE_ADMIN';

export const GET_PORTFOLIO_ADMIN = 'GET_PORTFOLIO_ADMIN';
export const GET_PORTFOLIO_SUCCESS_ADMIN = 'GET_PORTFOLIO_SUCCESS_ADMIN';
export const GET_PORTFOLIO_FAILURE_ADMIN = 'GET_PORTFOLIO_FAILURE_ADMIN';
export const POST_PORTFOLIO_ADMIN = 'POST_PORTFOLIO_ADMIN';
export const POST_PORTFOLIO_SUCCESS_ADMIN = 'POST_PORTFOLIO_SUCCESS_ADMIN';
export const POST_PORTFOLIO_FAILURE_ADMIN = 'POST_PORTFOLIO_FAILURE_ADMIN';

export const GET_EMAIL_ADMIN = 'GET_EMAIL_ADMIN';
export const GET_EMAIL_SUCCESS_ADMIN = 'GET_EMAIL_SUCCESS_ADMIN';
export const GET_EMAIL_FAILURE_ADMIN = 'GET_EMAIL_FAILURE_ADMIN';
export const POST_EMAIL_ADMIN = 'POST_EMAIL_ADMIN';
export const POST_EMAIL_SUCCESS_ADMIN = 'POST_EMAIL_SUCCESS_ADMIN';
export const POST_EMAIL_FAILURE_ADMIN = 'POST_EMAIL_FAILURE_ADMIN';
