version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    expose:
      - "3306"
    volumes:
      - ./backend/db:/var/lib/mysql
    environment:
       MYSQL_HOST: ${DB_HOST}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  backend:
    # image: python:3.6
    build: ./backend
    volumes:
      - ./backend/:/backend
    ports:
      - "8000:8000"
    # working_dir: /backend
    # command: sh entrypoint-backend.sh
    depends_on:
      - db
    links:
      - db
  frontend:
    # image: node:13.8.0-alpine
    # command: sh entrypoint-frontend.sh
    # working_dir: /frontend/website-ui
    build: ./frontend
    volumes:
      - ./frontend/:/frontend/
    ports:
      - "80:80"
  # nginx:
  #   # image: nginx:1.17.8-alpine
  #   build: ./frontend/website-ui
  #   ports:
  #     - 3000:8000
  #   volumes:
  #     - ./frontend/website-ui/build:/var/www/website
    # depends_on:
    #   - backend