version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    entrypoint: source .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - "${DB_PORT}"
    volumes:
      - ./backend/db:/var/lib/mysql
    environment:
       MYSQL_HOST: ${DB_HOST}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend
    ports:
      - "${BE_PORT}:${BE_PORT}"
    depends_on:
      - db
    links:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/frontend/
    ports:
      - "${FE_PORT}:${FE_PORT}"