# Generated by Django 3.0.3 on 2020-02-13 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
