# Generated by Django 3.0.3 on 2020-02-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='client_ip',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
