# Generated by Django 3.0.3 on 2020-02-23 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200223_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date_send',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
