# Generated by Django 3.0.3 on 2020-02-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_email_date_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='id',
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
